title: "CSCI/310 <small><small>v0.1.0</small></small>"
title_separator: "-"
author: CSBSJU
description: Course materials for CSCI 310.
lang: en-US
timezone: UTC
include:
  - docs/slides
exclude:
  - AUTHORS
  - LICENSE
  - LICENSE.MIT
  - assests/pep9
  - assests/slides

plugins:
  - jekyll-remote-theme
  
remote_theme: mmistakes/minimal-mistakes

defaults:
  - scope:
      path: ""
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_label: "Contents"
      toc_icon: "list-ul"
      sidebar:
        nav: "docs"
